#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 30 20:33:40 2019

@author: alflo
"""

from flatten_json import flatten
from os import listdir
from os.path import isfile, join
import matplotlib.pyplot as plt
import collections

##########importation ############

chemin = '/home/alflo/Bureau/course_v1'
fichiers = [f for f in listdir(chemin) 
            if isfile(join(chemin, f))]

#########pour lire les fichiers du document#####
surnom_l=[]

for i in fichiers:
    #print(i)
    try:
        fichier = open("/home/alflo/Bureau/course_v1/{}".format(i), "r")
        R = fichier.read().strip()
        
        l= eval(R)
        #pprint.pprint(l)
        s_n=l["content"]['username']
        
        surnom_l.append(s_n)
        
        f=flatten(l)
    except:
        s_n="none"
        surnom_l.append(s_n)
     
######pratique la collection pour compter######
        
 
intervention_nom = collections.Counter(surnom_l).most_common(20)# Compte les 20 premiers
#print(">>>>>>>",type(intervention_nom))
intervention_nom=intervention_nom[-19:]
#print(">>>>>>>>>",intervention_nom)

########et un graph en barre########

f, ax1 = plt.subplots(figsize =(10,10))
plt.bar(*zip(*intervention_nom), width = 0.6, color = 'orange',    edgecolor = 'blue', linewidth = 5)
plt.xticks(rotation = 90)    
plt.xlabel('pseudo', fontsize = 20,color='blue')
plt.ylabel("Intervention",fontsize = 20,color='blue')

plt.title('Nombre d\'interventions par personne',fontsize = 20,color='blue')